### ISSUE TITLE
Published devtools-local-toolbox module does not contain index.js

### ISSUE THREAD

**Issue by zimbabao** [jasonLaster/console.html#1]
/console.html (master)$ npm start

> console.html@0.0.1 start os/console.html
> node bin/dev-server

module.js:457
    throw err;
    ^

Error: Cannot find module '../node_modules/devtools-local-toolbox/index'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/rgaunker/os/console.html/bin/dev-server.js:4:17)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

**Comment by jasonLaster** [comment]
thanks, i believe this has been resolved
